### ISSUE TITLE
Error in im FE-Modul "Navigationsleiste (Bootstrap)"

### ISSUE THREAD

**Issue by xantippe** [netzmacht-archive/contao-bootstrap#75]
im FE-Modul Navigationsleiste (Bootstrap) kommt beim Aufruf

```
Module

Warning: in_array() expects parameter 2 to be array, null given in system/modules/core/library/Contao/System.php on line 160

#0 [internal function]: __error(2, 'in_array() expe...', '/home/www/diagn...', 160, Array)
#1 system/modules/core/library/Contao/System.php(160): in_array('getInstance', NULL)
#2 system/modules/core/library/Contao/Widget.php(1388): Contao\System::importStatic('Netzmacht\\Boots...')
#3 composer/vendor/menatwork/contao-multicolumnwizard/system/modules/multicolumnwizard/MultiColumnWizard.php(941): Contao\Widget::getAttributesFromDca(Array, 'bootstrap_navba...', '65', NULL, 'tl_module', Object(MultiColumnWizard))
#4 composer/vendor/menatwork/contao-multicolumnwizard/system/modules/multicolumnwizard/MultiColumnWizard.php(479): MultiColumnWizard->initializeWidget(Array, 0, 'module', '65')
#5 system/modules/core/library/Contao/Widget.php(684): MultiColumnWizard->generate()
#6 system/modules/core/templates/backend/be_widget.html5(3): Contao\Widget->generateWithError(true)
#7 system/modules/core/library/Contao/BaseTemplate.php(88): include('/home/www/diagn...')
#8 system/modules/core/library/Contao/Widget.php(630): Contao\BaseTemplate->parse()
#9 system/modules/core/classes/DataContainer.php(546): Contao\Widget->parse()
#10 system/modules/core/drivers/DC_Table.php(1928): Contao\DataContainer->row('{title_legend},...')
#11 system/modules/core/classes/Backend.php(650): Contao\DC_Table->edit()
#12 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('themes')
#13 contao/main.php(20): Contao\BackendMain->run()
#14 {main}


Fatal error: Class 'Netzmacht\Bootstrap\Panel\Dca\Module' not found in /home/www/mywebsite/system/modules/core/library/Contao/System.php on line 160

```

contao-bootstrap/bundle 	1.0.0
Contao 3.5.3

**Comment by dmolineus** [comment]
Bitte im richtigen Ticketsystem erstellen: https://github.com/contao-bootstrap. Bitte vorher überprüfen, ob Composer alles richtig installiert hat.

**Comment by xantippe** [comment]
o.k.
https://github.com/contao-bootstrap/navigation/issues/11

Composr meldet, es gäbe nix zum Updaten...
